
package jam.peptide;

import jam.app.JamEnv;

/**
 * Enumerates standard collections of peptides.
 */
public enum ReferencePeptidome {
    /**
     * 9-mer peptides generated by the (pre-MHC) proteasome and TAP
     * processing in the thymic cortex and medulla.
     */
    THYMIC9("THYPEP_THYMIC9_REFERENCE");

    private final String envName;
    private Peptidome peptides;

    private ReferencePeptidome(String envName) {
        this.envName = envName;
        this.peptides = null;
    }

    /**
     * Returns the reference peptidome.
     *
     * @return the reference peptidome.
     */
    public Peptidome getPeptides() {
        if (peptides == null)
            peptides = Peptidome.load(JamEnv.getRequired(envName));

        return peptides;
    }
}
