
package jam.collect;

import java.util.HashMap;
import java.util.function.Function;

/**
 * Implements the {@code MapView} interface using an in-memory
 * {@code HashMap} for record storage.
 *
 * @param <K> the runtime type of the record key.
 *
 * @param <V> the runtime type of the view records.
 */
public class HashMapView<K, V> extends AbstractMapView<K, V> {
    /**
     * Creates a new view over an existing {@code HashMap}.
     *
     * @param map the backing map for record storage.
     */
    protected HashMapView(HashMap<K, V> map) {
        super(map);
    }

    /**
     * Creates a new view populated by a collection of records.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param records the initial contents of the view.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new view containing the specified records with
     * keys generated by the input function.
     */
    public static <K, V> HashMapView<K, V> create(Iterable<V> records, Function<V, K> keyFunc) {
        HashMap<K, V> map = new HashMap<K, V>();

        for (V record : records)
            map.put(keyFunc.apply(record), record);

        return new HashMapView<K, V>(map);
    }
}

