
package jam.collect;

import java.util.Collection;
import java.util.function.Function;

import com.google.common.collect.HashMultimap;

/**
 * Implements the {@code MapTable} interface using an in-memory
 * {@code HashMulti} for record storage.
 *
 * @param <K> the runtime type of the record key.
 *
 * @param <V> the runtime type of the table records.
 */
public class HashMultiTable<K, V> extends AbstractMultiTable<K, V> {
    private HashMultiTable(HashMultimap<K, V> backMap, Function<V, K> keyFunc) {
        super(backMap, keyFunc);
    }

    /**
     * Creates a new empty table.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new empty table with the specified key-generating
     * function.
     */
    public static <K, V> HashMultiTable<K, V> create(Function<V, K> keyFunc) {
        return new HashMultiTable<K, V>(HashMultimap.create(), keyFunc);
    }

    /**
     * Creates a new table populated by a collection of records.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param records the initial contents of the table.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new table containing the specified records with
     * keys generated by the input function.
     */
    public static <K, V> HashMultiTable<K, V> create(Collection<V> records, Function<V, K> keyFunc) {
        HashMultiTable<K, V> table = create(keyFunc);
        table.store(records);
        return table;
    }
}

