
package jam.collect;

import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.function.Function;

/**
 * Implements the {@code MapTable} interface using an in-memory map
 * for record storage.
 *
 * @param <K> the runtime type of the record key.
 *
 * @param <V> the runtime type of the table records.
 */
public class MapCache<K, V> implements MapTable<K, V> {
    /**
     * The underlying map storage.
     */
    protected final Map<K, V> backMap;

    /**
     * The function that extracts keys from records.
     */
    protected final Function<V, K> keyFunc;

    /**
     * Creates a new cache with an underlying map for storage and a
     * function to extract keys from records.
     *
     * @param backMap the backing map for record storage.
     *
     * @param keyFunc a function to extract keys from records.
     */
    public MapCache(Map<K, V> backMap, Function<V, K> keyFunc) {
        this.backMap = backMap;
        this.keyFunc = keyFunc;
    }

    /**
     * Creates a new empty cache backed by a {@code HashMap}.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new empty cache with the specified key-generating
     * function.
     */
    public static <K, V> MapCache<K, V> hash(Function<V, K> keyFunc) {
        return new MapCache<K, V>(new HashMap<K, V>(), keyFunc);
    }

    /**
     * Creates a new cache backed by a {@code HashMap}.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param records the records to store.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new cache containing the specified records with
     * keys generated by the input function.
     */
    public static <K, V> MapCache<K, V> hash(Collection<V> records, Function<V, K> keyFunc) {
        MapCache<K, V> cache = hash(keyFunc);
        cache.store(records);
        return cache;
    }

    /**
     * Creates a new empty cache backed by a {@code TreeMap}.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new empty cache with the specified key-generating
     * function.
     */
    public static <K, V> MapCache<K, V> tree(Function<V, K> keyFunc) {
        return new MapCache<K, V>(new TreeMap<K, V>(), keyFunc);
    }

    /**
     * Creates a new cache backed by a {@code TreeMap}.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the records values.
     *
     * @param records the records to store.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new cache containing the specified records with
     * keys generated by the input function.
     */
    public static <K, V> MapCache<K, V> tree(Collection<V> records, Function<V, K> keyFunc) {
        MapCache<K, V> cache = tree(keyFunc);
        cache.store(records);
        return cache;
    }

    /**
     * Extracts the key from a record.
     *
     * @param record the record of interest.
     *
     * @return the key for the specified record.
     */
    public K getKey(V record) {
        return keyFunc.apply(record);
    }

    @Override public int count() {
        return backMap.size();
    }

    @Override public void delete() {
        backMap.clear();
    }

    @Override public boolean delete(V record) {
        return backMap.remove(getKey(record)) != null;
    }

    @Override public Collection<V> fetch() {
        return Collections.unmodifiableCollection(backMap.values());
    }

    @Override public V fetch(K key) {
        return backMap.get(key);
    }

    @Override public Set<K> keys() {
        return Collections.unmodifiableSet(backMap.keySet());
    }


    @Override public void store(V record) {
        backMap.put(getKey(record), record);
    }

    /**
     * Throws an {@code UnsupportedOperationException}: use
     * {@code equalsView} for equality tests.
     *
     * @throws UnsupportedOperationException in all cases.
     */
    @Override public boolean equals(Object obj) {
        throw new UnsupportedOperationException("Use MapView::equalsView for equality tests.");
    }

    /**
     * Throws an {@code UnsupportedOperationException}: views are not
     * suitable as hash keys.
     *
     * @throws UnsupportedOperationException in all cases.
     */
    @Override public int hashCode() {
        throw new UnsupportedOperationException("Views are not suitable for hash keys.");
    }

    /**
     * Returns a string containing every mapping in this view.
     *
     * @return a string containing every mapping in this view.
     */
    @Override public String toString() {
        return backMap.toString();
    }
}

