
package jam.collect;

import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.function.Function;

/**
 * Implementats the {@code JamTable} interface using a map for the
 * underlying storage.
 */
public class MapTable<K, V> implements JamTable<K, V> {
    /**
     * The backing map.
     */
    protected final Map<K, V> backMap;

    /**
     * The function that extracts keys from records.
     */
    protected final Function<V, K> keyFunc;

    /**
     * Creates a new table with an underlying map for storage and a
     * function to extract keys from records.
     *
     * @param backMap the backing map for record storage.
     *
     * @param keyFunc a function to extract keys from records.
     */
    protected MapTable(Map<K, V> backMap, Function<V, K> keyFunc) {
        this.backMap = backMap;
        this.keyFunc = keyFunc;
    }

    /**
     * Creates a new empty map table backed by a {@code HashMap}.
     *
     * @param <K> the runtime time for the map keys.
     *
     * @param <V> the runtime time for the map values.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new empty map table with the specified key-generating
     * function.
     */
    public static <K, V> MapTable<K, V> hash(Function<V, K> keyFunc) {
        return new MapTable<K, V>(new HashMap<K, V>(), keyFunc);
    }

    /**
     * Creates a new map table backed by a {@code HashMap}.
     *
     * @param <K> the runtime time for the map keys.
     *
     * @param <V> the runtime time for the map values.
     *
     * @param records the records to store.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new map table containing the specified records with
     * keys generated by the input function.
     */
    public static <K, V> MapTable<K, V> hash(Collection<V> records, Function<V, K> keyFunc) {
        return new MapTable<K, V>(JamMaps.hash(records, keyFunc), keyFunc);
    }

    /**
     * Creates a new empty map table backed by a {@code TreeMap}.
     *
     * @param <K> the runtime time for the map keys.
     *
     * @param <V> the runtime time for the map values.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new empty map table with the specified key-generating
     * function.
     */
    public static <K, V> MapTable<K, V> tree(Function<V, K> keyFunc) {
        return new MapTable<K, V>(new TreeMap<K, V>(), keyFunc);
    }

    /**
     * Creates a new map table backed by a {@code TreeMap}.
     *
     * @param <K> the runtime time for the map keys.
     *
     * @param <V> the runtime time for the map values.
     *
     * @param records the records to store.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new map table containing the specified records with
     * keys generated by the input function.
     */
    public static <K, V> MapTable<K, V> tree(Collection<V> records, Function<V, K> keyFunc) {
        return new MapTable<K, V>(JamMaps.tree(records, keyFunc), keyFunc);
    }

    /**
     * Identifies keys contained in this table.
     *
     * @param key the key to search for.
     *
     * @return {@code true} iff this table contains a record with the
     * specified key.
     */
    @Override public boolean contains(K key) {
        return backMap.containsKey(key);
    }

    /**
     * Returns the number of records in this table.
     *
     * @return the number of records in this table.
     */
    @Override public int count() {
        return backMap.size();
    }

    /**
     * Deletes all records from this table.
     */
    @Override public void delete() {
        backMap.clear();
    }

    /**
     * Deletes the record indexed by a given key (a no-op if there is
     * no matching record).
     *
     * @param key the key of the record to delete.
     *
     * @return {@code true} iff the matching record was deleted.
     */
    @Override public boolean delete(K key) {
        return backMap.remove(key) != null;
    }

    /**
     * Extracts the key field from a record.
     *
     * @param record a record to examine.
     *
     * @return the key field for the specified record.
     */
    @Override public K getKey(V record) {
        return keyFunc.apply(record);
    }

    /**
     * Inserts a new record into this table; this operation will fail
     * if this table already contains a record with the same key.
     *
     * @param record the record to insert.
     *
     * @return {@code true} iff the record was successfully inserted.
     */
    @Override public boolean insert(V record) {
        K key = getKey(record);

        if (contains(key))
            return false;

        backMap.put(getKey(record), record);
        return true;
    }

    /**
     * Returns a read-only view of the keys in this table.
     *
     * @return a read-only view of the keys in this table.
     */
    @Override public Set<K> keys() {
        return Collections.unmodifiableSet(backMap.keySet());
    }

    /**
     * Returns all records in this table.
     *
     * @return all records in this table.
     */
    @Override public Collection<V> select() {
        return Collections.unmodifiableCollection(backMap.values());
    }

    /**
     * Returns the record indexed by a given key.
     *
     * @param key the key of the record to select.
     *
     * @return the record with the specified key (or
     * {@code null} if there is no matching record).
     */
    @Override public V select(K key) {
        return backMap.get(key);
    }

    /**
     * Updates an existing record in this table; this operation will
     * fail unless this table already contains a record with the same
     * key.
     *
     * @param record the record to update.
     *
     * @return {@code true} iff the record was successfully updated.
     */
    @Override public boolean update(V record) {
        K key = getKey(record);

        if (!contains(key))
            return false;

        backMap.put(getKey(record), record);
        return true;
    }

    /**
     * Inserts a new record or updates an existing record in this
     * table; this operation should always succeed.
     *
     * @param record the record to insert or update.
     */
    @Override public void upsert(V record) {
        backMap.put(getKey(record), record);
    }

    @Override public boolean equals(Object obj) {
        throw new UnsupportedOperationException("Use TableView::equalsView for equality tests.");
    }

    @Override public int hashCode() {
        throw new UnsupportedOperationException("Views are not suitable for hash keys.");
    }

    @Override public String toString() {
        return backMap.toString();
    }
}
