
package jam.collect;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Set;
import java.util.function.Function;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;

/**
 * Implements the {@code MultiTable} interface using an in-memory
 * multimap for record storage.
 *
 * @param <K> the runtime type of the record key.
 *
 * @param <V> the runtime type of the table records.
 */
public class MultiCache<K, V> implements MultiTable<K, V> {
    /**
     * The underlying multimap storage.
     */
    protected final SetMultimap<K, V> backMap;

    /**
     * The function that extracts keys from records.
     */
    protected final Function<V, K> keyFunc;

    /**
     * Creates a new cache with an underlying map for storage and a
     * function to extract keys from records.
     *
     * @param backMap the backing map for record storage.
     *
     * @param keyFunc a function to extract keys from records.
     */
    public MultiCache(SetMultimap<K, V> backMap, Function<V, K> keyFunc) {
        this.backMap = backMap;
        this.keyFunc = keyFunc;
    }

    /**
     * Creates a new empty cache backed by a {@code HashMultimap}.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new empty cache with the specified key-generating
     * function.
     */
    public static <K, V> MultiCache<K, V> hash(Function<V, K> keyFunc) {
        return new MultiCache<K, V>(HashMultimap.create(), keyFunc);
    }

    /**
     * Creates a new cache backed by a {@code HashMultimap}.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param records the records to store.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new cache containing the specified records with
     * keys generated by the input function.
     */
    public static <K, V> MultiCache<K, V> hash(Collection<V> records, Function<V, K> keyFunc) {
        MultiCache<K, V> cache = hash(keyFunc);
        cache.store(records);
        return cache;
    }

    /**
     * Extracts the key from a record.
     *
     * @param record the record of interest.
     *
     * @return the key for the specified record.
     */
    public K getKey(V record) {
        return keyFunc.apply(record);
    }

    @Override public int count() {
        return backMap.size();
    }

    @Override public void delete() {
        backMap.clear();
    }

    @Override public boolean delete(V record) {
        return backMap.remove(getKey(record), record);
    }

    @Override public Collection<V> fetch() {
        return Collections.unmodifiableCollection(backMap.values());
    }

    @Override public Set<V> fetch(K key) {
        return Collections.unmodifiableSet(backMap.get(key));
    }

    @Override public Set<K> keys() {
        return Collections.unmodifiableSet(backMap.keySet());
    }

    @Override public void store(V record) {
        backMap.put(getKey(record), record);
    }

    /**
     * Throws an {@code UnsupportedOperationException}: use
     * {@code equalsView} for equality tests.
     *
     * @throws UnsupportedOperationException in all cases.
     */
    @Override public boolean equals(Object obj) {
        throw new UnsupportedOperationException("Use MultiView::equalsView for equality tests.");
    }

    /**
     * Throws an {@code UnsupportedOperationException}: views are not
     * suitable as hash keys.
     *
     * @throws UnsupportedOperationException in all cases.
     */
    @Override public int hashCode() {
        throw new UnsupportedOperationException("Views are not suitable for hash keys.");
    }

    /**
     * Returns a string containing every mapping in this view.
     *
     * @return a string containing every mapping in this view.
     */
    @Override public String toString() {
        return backMap.toString();
    }
}
