
package jam.collect;

import java.util.Collection;
import java.util.function.Function;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;

/**
 * Implements the {@code MultiTable} interface using an in-memory
 * multimap for record storage.
 *
 * @param <K> the runtime type of the record key.
 *
 * @param <V> the runtime type of the table records.
 */
public class MultiCache<K, V> extends MultiWrapper<K, V> implements MultiTable<K, V> {
    /**
     * The function that extracts keys from records.
     */
    protected final Function<V, K> keyFunc;

    /**
     * Creates a new cache with an underlying map for storage and a
     * function to extract keys from records.
     *
     * @param backMap the backing map for record storage.
     *
     * @param keyFunc a function to extract keys from records.
     */
    public MultiCache(SetMultimap<K, V> backMap, Function<V, K> keyFunc) {
        super(backMap);
        this.keyFunc = keyFunc;
    }

    /**
     * Creates a new empty cache backed by a {@code HashMultimap}.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new empty cache with the specified key-generating
     * function.
     */
    public static <K, V> MultiCache<K, V> hash(Function<V, K> keyFunc) {
        return new MultiCache<K, V>(HashMultimap.create(), keyFunc);
    }

    /**
     * Creates a new cache backed by a {@code HashMultimap}.
     *
     * @param <K> the runtime type for the record keys.
     *
     * @param <V> the runtime type for the record values.
     *
     * @param records the records to store.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new cache containing the specified records with
     * keys generated by the input function.
     */
    public static <K, V> MultiCache<K, V> hash(Collection<V> records, Function<V, K> keyFunc) {
        MultiCache<K, V> cache = hash(keyFunc);
        cache.store(records);
        return cache;
    }

    /**
     * Extracts the key from a record.
     *
     * @param record the record of interest.
     *
     * @return the key for the specified record.
     */
    public K getKey(V record) {
        return keyFunc.apply(record);
    }

    @Override public void delete() {
        map.clear();
    }

    @Override public boolean delete(V record) {
        return map.remove(getKey(record), record);
    }

    @Override public void store(V record) {
        map.put(getKey(record), record);
    }
}
