
package jam.collect;

import java.util.Collection;
import java.util.function.Function;

/**
 * Defines a mutable table of records indexed by one-to-many mapping
 * for a given key class.
 *
 * @param <K> the runtime type of the record key.
 *
 * @param <V> the runtime type of the table records.
 */
public interface MultiTable<K, V> extends MultiView<K, V>, RecordStore<V> {
    /**
     * Creates a new empty table backed by a {@code HashMultimap}.
     *
     * @param <K> the runtime type for the map keys.
     *
     * @param <V> the runtime type for the map values.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new empty table with the specified key-generating
     * function.
     */
    public static <K, V> MultiTable<K, V> hash(Function<V, K> keyFunc) {
        return HashMultiTable.create(keyFunc);
    }

    /**
     * Creates a new table backed by a {@code HashMultimap}.
     *
     * @param <K> the runtime type for the map keys.
     *
     * @param <V> the runtime type for the map values.
     *
     * @param records the records to store.
     *
     * @param keyFunc a function to generate keys for the records.
     *
     * @return a new table containing the specified records with
     * keys generated by the input function.
     */
    public static <K, V> MultiTable<K, V> hash(Collection<V> records, Function<V, K> keyFunc) {
        return HashMultiTable.create(records, keyFunc);
    }
}
